$items = array(
		'Autoreifen',
		'Bessenschrank',
		'Bett: Doppelbett',
		'Bett: Einzelbett',
		'Bett: Etagenbett',
		'Bett: Franz.',
		'Bett: Kinderbett',
		'Bilder über 0,8m',
		'Blumenkübel / Kasten',
		'Bücherkisten',
		'Bücherregal nicht zerlegb. je m',
		'Bücherregal zerlegb. je angf. m',
		'Büffet mit Aufsatz',
		'Büffet mit Aufsätzen',
		'Büro Container',
		'Deckenlampe',
		'Dreirad / Kinderrad',
		'Eckbank je Sitz',
		'EDV-Anlage',
		'Fahrrad / Moped',
		'Fernseher',
		'Fernsehtisch / -schränkchen',
		'Garderobe / Hut- Kleiderablage',
		'Geschirrspülmaschine',
		'Herd',
		'Hängeschrank je Tür',
		'Karton',
		'Kinderwagen',
		'Klapptisch / Klappstuhl',
		'Kleiderbox',
		'Koffer',
		'Kommode / Truhe',
		'Kühlschrank bis 120l',
		'Kühlschrank über 120l',
		'Leiter je angef. m',
		'Mikrowelle',
		'Musikschrank / Turm',
		'Mültonne',
		'Nachttisch',
		'Nähmaschine (Schrank)',
		'Pflanze 0,7-1,5m',
		'Rasenmäher / Motor',
		'Regal nicht zerlegbar',
		'Regal zerlegbar je angef. m',
		'Schrank bis 2 Türen, nicht zerlegbar',
		'Schrank zerlegbar je angef, m',
		'Schreibtisch bis 1,6m',
		'Schreibtisch über 1,6m',
		'Schreibtischstuhl',
		'Schuhschrank',
		'Sekretär',
		'Sessel mit Armlehnen',
		'Sessel ohne Armlehnen',
		'Sideboard',
		'Sofa / Couch / Liege, je Sitz',
		'Spiegel über 0,8m',
		'Standuhr',
		'Stehlampe',
		'Stuhl / Hocker',
		'Stuhl mit Armlehne',
		'Stuhl ohne Armlehnen',
		'Teppich',
		'Tisch bis 1,2m',
		'Tisch über 1,2m',
		'Toilettenschrank',
		'Unterschrank je Tür',
		'Vitrine / Glasschrank',
		'Waschmaschine / Trockner',
		'Werkbank zerlegbar',
		'Werkzeugkoffer',
		'Werkzeugschrank',
		'Wohnz.-Schrank zerlegb. je angef. m',
		'Wäscheschrank',
		'Wäschetruhe',
    );
